// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrixSubcol
Rcpp::NumericVector matrixSubcol(Rcpp::NumericMatrix x, int i0, int i1, int icol);
RcppExport SEXP _MethodOfFragments_matrixSubcol(SEXP xSEXP, SEXP i0SEXP, SEXP i1SEXP, SEXP icolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type i0(i0SEXP);
    Rcpp::traits::input_parameter< int >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< int >::type icol(icolSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixSubcol(x, i0, i1, icol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rprintf
void rcpp_rprintf(NumericVector v);
RcppExport SEXP _MethodOfFragments_rcpp_rprintf(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_rprintf(v);
    return R_NilValue;
END_RCPP
}
// order_
IntegerVector order_(NumericVector x);
RcppExport SEXP _MethodOfFragments_order_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(order_(x));
    return rcpp_result_gen;
END_RCPP
}
// any_sug
bool any_sug(LogicalVector x);
RcppExport SEXP _MethodOfFragments_any_sug(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(any_sug(x));
    return rcpp_result_gen;
END_RCPP
}
// all_sug
bool all_sug(LogicalVector x);
RcppExport SEXP _MethodOfFragments_all_sug(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(all_sug(x));
    return rcpp_result_gen;
END_RCPP
}
// find_row
int find_row(NumericMatrix m, NumericVector v);
RcppExport SEXP _MethodOfFragments_find_row(SEXP mSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(find_row(m, v));
    return rcpp_result_gen;
END_RCPP
}
// getrmseiTemp
NumericVector getrmseiTemp(int Npdt, IntegerVector mObs, IntegerVector mSim, NumericMatrix Yobs24, NumericMatrix Ysim24, int i);
RcppExport SEXP _MethodOfFragments_getrmseiTemp(SEXP NpdtSEXP, SEXP mObsSEXP, SEXP mSimSEXP, SEXP Yobs24SEXP, SEXP Ysim24SEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Npdt(NpdtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mObs(mObsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mSim(mSimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yobs24(Yobs24SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ysim24(Ysim24SEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(getrmseiTemp(Npdt, mObs, mSim, Yobs24, Ysim24, i));
    return rcpp_result_gen;
END_RCPP
}
// disagTempMOF
List disagTempMOF(int Npdt, IntegerVector mObs, IntegerVector mSim, NumericMatrix YobsXX, NumericMatrix Yobs24, NumericMatrix Ysim24);
RcppExport SEXP _MethodOfFragments_disagTempMOF(SEXP NpdtSEXP, SEXP mObsSEXP, SEXP mSimSEXP, SEXP YobsXXSEXP, SEXP Yobs24SEXP, SEXP Ysim24SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Npdt(NpdtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mObs(mObsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mSim(mSimSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type YobsXX(YobsXXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yobs24(Yobs24SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ysim24(Ysim24SEXP);
    rcpp_result_gen = Rcpp::wrap(disagTempMOF(Npdt, mObs, mSim, YobsXX, Yobs24, Ysim24));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MethodOfFragments_matrixSubcol", (DL_FUNC) &_MethodOfFragments_matrixSubcol, 4},
    {"_MethodOfFragments_rcpp_rprintf", (DL_FUNC) &_MethodOfFragments_rcpp_rprintf, 1},
    {"_MethodOfFragments_order_", (DL_FUNC) &_MethodOfFragments_order_, 1},
    {"_MethodOfFragments_any_sug", (DL_FUNC) &_MethodOfFragments_any_sug, 1},
    {"_MethodOfFragments_all_sug", (DL_FUNC) &_MethodOfFragments_all_sug, 1},
    {"_MethodOfFragments_find_row", (DL_FUNC) &_MethodOfFragments_find_row, 2},
    {"_MethodOfFragments_getrmseiTemp", (DL_FUNC) &_MethodOfFragments_getrmseiTemp, 6},
    {"_MethodOfFragments_disagTempMOF", (DL_FUNC) &_MethodOfFragments_disagTempMOF, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MethodOfFragments(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
