# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixSubcol <- function(x, i0, i1, icol) {
    .Call(`_MethodOfFragments_matrixSubcol`, x, i0, i1, icol)
}

rcpp_rprintf <- function(v) {
    invisible(.Call(`_MethodOfFragments_rcpp_rprintf`, v))
}

order_ <- function(x) {
    .Call(`_MethodOfFragments_order_`, x)
}

any_sug <- function(x) {
    .Call(`_MethodOfFragments_any_sug`, x)
}

all_sug <- function(x) {
    .Call(`_MethodOfFragments_all_sug`, x)
}

find_row <- function(m, v) {
    .Call(`_MethodOfFragments_find_row`, m, v)
}

getrmseiTemp <- function(Npdt, mObs, mSim, Yobs24, Ysim24, i) {
    .Call(`_MethodOfFragments_getrmseiTemp`, Npdt, mObs, mSim, Yobs24, Ysim24, i)
}

disagTempMOF <- function(Npdt, mObs, mSim, YobsXX, Yobs24, Ysim24) {
    .Call(`_MethodOfFragments_disagTempMOF`, Npdt, mObs, mSim, YobsXX, Yobs24, Ysim24)
}

